spring:
     application:
          name: ReviewPlatform
     liquibase:
          enabled: true
          change-log: db/changelog/db.changelog-master.xml
     datasource:
          url: ${DB_URL}
          username: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          driver-class-name: org.postgresql.Driver
jwt:
     secret: ${JWT_SECRET}
     expiration: ${JWT_EXPIRATION:900000} # 15 minutes
springdoc:
     swagger-ui:
          path: /api-docs.html